Aman Kumar Mahato<br>
L5CG13<br>
Worksheet_1


**TO - DO - Task**<br>
**Please complete all the problem listed below.**

**Problem - 1: Array Creation:<br>
Complete the following Tasks:**

1. Initialize an empty array with size 2X2.

In [3]:
import numpy as np
empty_array = np.empty((2, 2))
empty_array

array([[2.12199579e-314, 0.00000000e+000],
       [5.21733322e-321, 6.95293141e-310]])

2. Initialize an all one array with size 4X2.

In [6]:
one_array = np.ones((4, 2))
one_array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [13]:
new_array = np.full((4,5),6)
new_array

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [23]:
new_zeros = np.zeros_like(new_array)
new_zeros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [24]:
new_ones = np.ones_like(new_array)
new_ones

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [30]:
new_list = [1,2,3,4]
a = np.array(new_list)
a


array([1, 2, 3, 4])

**Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:**

Complete the following tasks:<br>
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [35]:
a = np.arange(10,50)
a


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

2. Create a 3X3 matrix with values ranging from 0 to 8.<br>
{Hint:look for np.reshape()}

In [40]:
b = np.arange((9))
b = np.reshape(b, (3,3))
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [42]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

4. Create a random array of size 30 and find the mean of the array.<br>
{Hint:check for np.random.random() and array.mean() function}

In [51]:
a = np.random.random(30)
print(a)
b = a.mean()
print("Mean: ", b)

[0.2929841  0.46875627 0.54544492 0.76021685 0.16987511 0.37104063
 0.91295521 0.71172071 0.64839188 0.36847747 0.35885691 0.34051012
 0.83696977 0.22940623 0.54805151 0.853007   0.00405231 0.14531637
 0.84080661 0.41048537 0.62878058 0.92838084 0.18464444 0.10165458
 0.32138984 0.36294428 0.33843037 0.46928069 0.3688393  0.25824104]
Mean:  0.45933037667160675


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [68]:
r = np.random.random(100)
s = np.reshape(r,(10,10))
min = s.min()
max = s.max()
print("Min: ", min)
print("Min: ", max)



Min:  0.008271851363867877
Min:  0.9998970091612058


6. Create a zero array of size 10 and replace 5th element with 1.

In [65]:
zero = np.zeros(10)
np.put(zero, 4, 1)
print(zero)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [72]:
arr = [1,2,0,0,4,0]
a = np.flip(arr)
print(a)

[0 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside.

In [79]:
a = np.ones((5,5))
print(a)
a[1:-1, 1:-1] = 0
a

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [97]:
a = np.zeros((8,8))
a[1::2,::2]=1
a[::2,1::2]=1
a


array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

Problem - 3: Array Operations: <br>
For the following arrays: <br>
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]); <br>
v = np.array([9,10]) and w = np.array([11,12]); <br>
Complete all the task using numpy:

In [3]:
import numpy as np
x = np.array([[1,2],[3,5]]) 
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# 1.Add two array
print("Add: ",x+y)

#2. Subtract the two array.
print("Subtract: ", w-v)
# 3. Multiply the array with any integers of your choice.
print("Multiply: ", x*y)
# 4. Find the square of each element of the array.
print("Square ", y*y)
# 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
print("Dot Product between v and w: ", np.dot(v,w))
print("Dot Product between x and v: ", np.dot(x,v))
print("Dot Product between x and y: ", np.dot(x,y))
# 6. Concatenate x(and)y along row and Concatenate v(and)w along column.
# {Hint:try np.concatenate() or np.vstack() functions.
v_reshaped = v.reshape(1, 2)  # Shape becomes (1, 2)
result = np.concatenate((x, v_reshaped), axis=0)  # Concatenate along rows
print("Concatenate x(and)y along row: ", result)
# 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?



Add:  [[ 6  8]
 [10 13]]
Subtract:  [2 2]
Multiply:  [[ 5 12]
 [21 40]]
Square  [[25 36]
 [49 64]]
Dot Product between v and w:  219
Dot Product between x and v:  [29 77]
Dot Product between x and y:  [[19 22]
 [50 58]]
Concatenate x(and)y along row:  [[ 1  2]
 [ 3  5]
 [ 9 10]]


**Problem - 4: Matrix Operations:** <br>
• For the following arrays:<br>
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);<br>
Prove following with Numpy:

In [6]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
A_inv = np.linalg.inv(A)
result = np.dot(A, A_inv)
I = np.eye(2)

#1. Prove A.A−1 = I.
print("A * A_inverse =", result)
print("Is A * A_inverse equal to I? ", np.allclose(result, I))
AB = np.dot(A, B)
BA = np.dot(B, A)

#2. Prove AB ̸= BA.
print("AB = \n", AB)
print("BA = \n", BA)
print("Is AB equal to BA? ", np.array_equal(AB, BA))

#3. Prove (AB)T = BTAT
AB_transpose = np.transpose(np.dot(A, B))
BT_AT = np.dot(B.T, A.T)
print("(AB)^T = \n", AB_transpose)
print("B^T A^T = \n", BT_AT)
print("Is (AB)^T equal to B^T A^T? ", np.allclose(AB_transpose, BT_AT))


A * A_inverse = [[1.0000000e+00 4.4408921e-16]
 [0.0000000e+00 1.0000000e+00]]
Is A * A_inverse equal to I?  True
AB = 
 [[23 13]
 [51 29]]
BA = 
 [[36 44]
 [13 16]]
Is AB equal to BA?  False
(AB)^T = 
 [[23 51]
 [13 29]]
B^T A^T = 
 [[23 51]
 [13 29]]
Is (AB)^T equal to B^T A^T?  True


• Solve the following system of Linear equation using Inverse Methods.

In [8]:
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

print("Answer (x, y, z): ", X)
X_direct = np.linalg.solve(A, B)
print("Solving by using np.linalg.solve: ", X_direct)
